/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laligasantander;

import java.util.Arrays;

/**
 *
 * @author tarod
 */
public class Ventana extends javax.swing.JFrame {

    private final GestoraEquipo gestoraEquipos;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        gestoraEquipos = new GestoraEquipo(GestoraAlmacenamiento.leerEquipos());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpGenerarJornada = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPartidos = new javax.swing.JTable();
        bGenerar = new javax.swing.JButton();
        jpClasificacion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClasificacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tablaPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPartidos);

        bGenerar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bGenerar.setText("GENERAR");
        bGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpGenerarJornadaLayout = new javax.swing.GroupLayout(jpGenerarJornada);
        jpGenerarJornada.setLayout(jpGenerarJornadaLayout);
        jpGenerarJornadaLayout.setHorizontalGroup(
            jpGenerarJornadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGenerarJornadaLayout.createSequentialGroup()
                .addGroup(jpGenerarJornadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGenerarJornadaLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpGenerarJornadaLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(bGenerar)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jpGenerarJornadaLayout.setVerticalGroup(
            jpGenerarJornadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGenerarJornadaLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(bGenerar)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Generar Jornada", jpGenerarJornada);

        jpClasificacion.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jpClasificacionComponentShown(evt);
            }
        });

        tablaClasificacion.setAutoCreateRowSorter(true);
        tablaClasificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaClasificacion);

        javax.swing.GroupLayout jpClasificacionLayout = new javax.swing.GroupLayout(jpClasificacion);
        jpClasificacion.setLayout(jpClasificacionLayout);
        jpClasificacionLayout.setHorizontalGroup(
            jpClasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClasificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpClasificacionLayout.setVerticalGroup(
            jpClasificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpClasificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clasificación", jpClasificacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpClasificacionComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpClasificacionComponentShown
        Arrays.sort(gestoraEquipos.getLosEquipos());
        tablaClasificacion.setModel(new ModeloTablaClasificacion(gestoraEquipos.getLosEquipos()));
    }//GEN-LAST:event_jpClasificacionComponentShown

    private void bGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGenerarActionPerformed
        tablaPartidos.setModel(new ModeloTablaJornada(gestoraEquipos.generarPartidos()));
    }//GEN-LAST:event_bGenerarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        GestoraAlmacenamiento.escribirEquipos(gestoraEquipos.getLosEquipos());
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGenerar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpClasificacion;
    private javax.swing.JPanel jpGenerarJornada;
    private javax.swing.JTable tablaClasificacion;
    private javax.swing.JTable tablaPartidos;
    // End of variables declaration//GEN-END:variables
}
